spring.application.name=result-view
spring.datasource.url=jdbc:mysql://localhost:3306/resultview
spring.datasource.username=root
spring.datasource.password=swayam2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true